### ISSUE TITLE
Redirect url when not on mobile sends the user to invalid page +

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/orakel#18]
- Link til åpner i ny fane. Det gjør at man blokkeres av popup.
- OK på mobil, men fiks i vanlig.
 
Fra Andreas, kopierer inn det han skrev. Jeg fikser naturlig nok redirigeringsurl.
 
- Rapportering via knappen i Artsorakelet fungerer bra på mobil. Finner ingen feil. 
- Hvis jeg prøver det samme fra PC, så får jeg feilmeldingssiden.  
- Ved en treffprosent på 61 % fra orakelet, så blir “Usikker artsbestemmelse” automatisk haket av. Hvor lav må treffprosenten være før dette slår inn?

**Comment by WouterKoch** [comment]
Ser ut til å fungere nå
